name: CI

on:
    pull_request:
        branches:
            - '*'

env:
    JAVA_VERSION: '17'
    JAVA_DISTRIBUTION: 'temurin'

jobs:
    checkTests:
        runs-on: ubuntu-latest

        steps:
            # SETUP
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  java-version: ${{ env.JAVA_VERSION }}
                  distribution: ${{ env.JAVA_DISTRIBUTION }}
            # UNIT TESTS
            - name: Unit tests
              id: unitTests
              run: mvn clean test