name: CICD

on:
    push:
        branches:
            - 'main'

env:
    JAVA_VERSION: '17'
    JAVA_DISTRIBUTION: 'temurin'
    DOCKER_HUB_USERNAME: 'rbernabeulopez'
    SSH_COMMAND: sh 4-in-a-row/.deploy/deploy.sh

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # SETUP
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  java-version: ${{ env.JAVA_VERSION }}
                  distribution: ${{ env.JAVA_DISTRIBUTION }}
            # UPLOAD TO DOCKERHUB
            - name: Docker Login
              if: success()
              uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
              with:
                  username: ${{ env.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            -   name: Push To Dockerhub
                id: dockerhubPush
                run: mvn clean verify -P build-docker-image -DskipTests

            - name: Deploy by DockerHub
              image uses: appleboy/ssh-action@master
              id: deploy-image
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                password: ${{ secrets.SSH_PASSWORD }}
                port: ${{ secrets.SSH_PORT }}
                script: ${{ env.SSH_COMMAND }}